- CHANGELOG.md
- lib/appium_lib_core/common/command.rb
- lib/appium_lib_core/common/device.rb
- test/functional/android/android/device_test.rb
- test/unit/android/device_test.rb
- test/unit/ios/device_test.rb
- test/unit/script/commands_test.rb
session/:session_id/appium/device/keyevent #21
But it seems to Selendroid.(So, add a comment for it)
e.g.: https://github.com/appium/python-client/blob/9640bf1ed7f51ecc90e915c36fd6f442816e19b3/appium/webdriver/webdriver.py#L817
> add keyevent

- lib/appium_lib_core/common/command.rb
- lib/appium_lib_core/common/device.rb
- test/functional/android/android/device_test.rb
- test/unit/android/device_test.rb
- test/unit/script/commands_test.rb
ref: Add taking element screenshot for OSS module #32
> add take element screenshot for oss

- .rubocop.yml
- appium_lib_core.gemspec
- lib/appium_lib_core/common/base.rb
- lib/appium_lib_core/common/base/bridge.rb
- lib/appium_lib_core/common/base/driver.rb
- lib/appium_lib_core/common/base/msjsonwp_bridge.rb
- lib/appium_lib_core/common/base/w3c_bridge.rb
- lib/appium_lib_core/common/command.rb
- lib/appium_lib_core/driver.rb
- test/functional/android/webdriver/w3c_actions_test.rb
- test/functional/ios/driver_test.rb
- test/functional/ios/webdriver/w3c_actions_test.rb
- test/unit/script/commands_test.rb
https://github.com/appium/ruby_lib/issues
> add w3c touch action tests and some supports for w3c

- CHANGELOG.md
- lib/appium_lib_core/common/base/w3c_bridge.rb
- lib/appium_lib_core/common/command.rb
- test/functional/android/android/device_test.rb
- test/functional/android/android/search_context_test.rb
- test/functional/android/webdriver/device_test.rb
- test/unit/script/commands_test.rb
https://github.com/appium/ruby_lib/issues/739
> add some oss commands to w3c

- lib/appium_lib_core/common/base/bridge/w3c.rb
- lib/appium_lib_core/common/base/driver.rb
- lib/appium_lib_core/common/command.rb
- lib/appium_lib_core/common/device.rb
- test/unit/android/webdriver_w3c_test.rb
https://github.com/appium/ruby_lib/issues/739
> add get timeouts for w3c

- CHANGELOG.md
- lib/appium_lib_core.rb
- lib/appium_lib_core/android/device.rb
- lib/appium_lib_core/common/command.rb
- lib/appium_lib_core/common/device.rb
- lib/appium_lib_core/device/screen_record.rb
- lib/appium_lib_core/driver.rb
- lib/appium_lib_core/ios/xcuitest/device.rb
- test/test_helper.rb
- test/unit/android/device_test.rb
- test/unit/android/device_w3c_test.rb
- test/unit/ios/device_test.rb
- test/unit/ios/device_w3c_test.rb
Update screen recording commands #48
> move screen recording command to common

- .rubocop.yml
- CHANGELOG.md
- lib/appium_lib_core/android/device.rb
- lib/appium_lib_core/android/device/emulator.rb
- lib/appium_lib_core/android/emulator.rb
- lib/appium_lib_core/common/command.rb
- test/unit/android/device_test.rb
- test/unit/android/device_w3c_test.rb
- test/unit/ios/device_test.rb
- test/unit/ios/device_w3c_test.rb
- test/unit/script/commands_test.rb
- session/:session_id/appium/device/network_speed #20
- session/:session_id/appium/device/power_ac #19
- session/:session_id/appium/device/power_capacity #18
- session/:session_id/appium/device/gsm_voice #17
- session/:session_id/appium/device/gsm_signal #16
- session/:session_id/appium/device/gsm_call #15
- session/:session_id/appium/device/send_sms #14
> Add some emulator commands

- CHANGELOG.md
- lib/appium_lib_core/common/base/bridge/w3c.rb
- lib/appium_lib_core/common/base/driver.rb
- lib/appium_lib_core/common/command.rb
- test/functional/android/webdriver/device_test.rb
- test/functional/ios/webdriver/device_test.rb
- test/unit/android/webdriver_test.rb
- test/unit/android/webdriver_w3c_test.rb
- session_capabilities:  https://appium.io/docs/en/commands/session/get/
> Add session capabilities w3cmodule

- CHANGELOG.md
- lib/appium_lib_core/common/device.rb
- test/functional/android/android/device_test.rb
- test/functional/ios/ios/device_test.rb
https://github.com/search?q=org%3Aappium+viewportScreenshot&type=Code
> add viewportScreenshot

- CHANGELOG.md
- Rakefile
- docs/mobile_command.md
- lib/appium_lib_core/common/device.rb
- lib/appium_lib_core/ios/xcuitest/device.rb
- test/functional/ios/ios/device_test.rb
https://github.com/appium/ruby_lib_core/issues/64
> add getting performance in core as same as Android

- CHANGELOG.md
- lib/appium_lib_core/common/base/bridge.rb
- lib/appium_lib_core/driver.rb
- test/functional/android/android/device_test.rb
- test/functional/ios/ios/device_test.rb
- test/unit/android/webdriver_test.rb
- test/unit/android/webdriver_w3c_test.rb
create_session attempt to throw non-existent error type Appium::Core::Error::WebDriverError #66
> Fix error initialisation

- CHANGELOG.md
- lib/appium_lib_core/android/device.rb
- lib/appium_lib_core/common/command/common.rb
- lib/appium_lib_core/device.rb
- test/unit/ios/device_test.rb
https://github.com/appium/appium-xcuitest-driver/pull/664/files
> add is_keyboard_shown for iOS

- .rubocop.yml
- CHANGELOG.md
- lib/appium_lib_core/device.rb
- test/unit/android/device_test.rb
- test/unit/android/device_w3c_test.rb
---
- https://github.com/appium/appium-base-driver/pull/208/files
- https://github.com/appium/appium-uiautomator2-server/pull/157/files
- https://github.com/appium/java-client/pull/890/files
> add flags for key press

- lib/appium_lib_core/driver.rb
- test/unit/android/device/mjsonwp/commands_test.rb
- test/unit/android/device/mjsonwp/definition_test.rb
- test/unit/android/device/w3c/commands_test.rb
- test/unit/android/device/w3c/definition_test.rb
- test/unit/android/webdriver/mjsonwp/commands_test.rb
- test/unit/android/webdriver/w3c/commands_test.rb
- test/unit/ios/device/mjsonwp/commands_test.rb
- test/unit/ios/device/mjsonwp/definition_test.rb
- test/unit/ios/device/w3c/commands_test.rb
- test/unit/ios/device/w3c/definition_test.rb
add a test for `delegate_from_appium_driver` to reduce regression.
> Add tests for delegates

- lib/appium_lib_core/device.rb
> appended docstring for file management

- CHANGELOG.md
- lib/appium_lib_core/patch.rb
- test/unit/driver_test.rb
https://github.com/appium/ruby_lib/issues/801
> include ::Appium::Core::Base::SearchContext instead of ::Selenium::WebDriver::SearchContext

- CHANGELOG.md
- lib/appium_lib_core/driver.rb
- test/unit/common_test.rb
Unable to use URL as app path #106
> can set packages over http

- CHANGELOG.md
- lib/appium_lib_core/common/base/bridge.rb
> Remove redundant code

- CHANGELOG.md
- appium_lib_core.gemspec
We need _use default_move_duration #115_ for 3.14+
> set < 3.14

- README.md
- test/functional/android/android/device_test.rb
- test/functional/android/android/search_context_test.rb
- test/functional/android/driver_test.rb
- test/functional/android/patch_test.rb
- test/functional/android/webdriver/create_session_test.rb
- test/functional/android/webdriver/device_test.rb
- test/functional/android/webdriver/w3c_actions_test.rb
- test/functional/ios/driver_test.rb
- test/functional/ios/ios/device_test.rb
- test/functional/ios/ios/search_context_test.rb
- test/functional/ios/patch_test.rb
- test/functional/ios/webdriver/create_session_test.rb
- test/functional/ios/webdriver/device_test.rb
- test/functional/ios/webdriver/w3c_actions_test.rb
- test/test_helper.rb
- test/unit/android/device/mjsonwp/commands_test.rb
- test/unit/android/device/mjsonwp/definition_test.rb
- test/unit/android/device/w3c/commands_test.rb
- test/unit/android/device/w3c/definition_test.rb
- test/unit/android/webdriver/mjsonwp/commands_test.rb
- test/unit/android/webdriver/w3c/commands_test.rb
- test/unit/driver_test.rb
- test/unit/image_element_test.rb
- test/unit/ios/device/mjsonwp/commands_test.rb
- test/unit/ios/device/mjsonwp/definition_test.rb
- test/unit/ios/device/w3c/commands_test.rb
- test/unit/ios/device/w3c/definition_test.rb
Add an example to run tests in parallel with "parallel_tests" gem
> add parallel tests for iOS as an example

- CHANGELOG.md
- lib/appium_lib_core/common/base/bridge/mjsonwp.rb
- test/unit/android/device/mjsonwp/commands_test.rb
- test/unit/android/device/w3c/commands_test.rb
> lib/appium_lib_core/common/base/screenshot.rb
> 100.0 % covered
> tweak screenshot tests

- lib/appium_lib_core/common/base/bridge/w3c.rb
- lib/appium_lib_core/common/base/driver.rb
- test/functional/android/webdriver/w3c_actions_test.rb
- test/test_helper.rb
- test/unit/android/webdriver/w3c/actions_test.rb
https://github.com/appium/appium/blob/0abdf00876b583ffa8e19c346bd9f7e74f6a884c/commands-yml/commands/interactions/actions.yml
> add send_actions for w3c multiple actions

- CHANGELOG.md
- appium_lib_core.gemspec
- lib/appium_lib_core/common/base/bridge/w3c.rb
https://github.com/appium/ruby_lib_core/issues/149
> use selenium 3.14.1

- CHANGELOG.md
- README.md
- lib/appium_lib_core/driver.rb
- test/functional/android/driver_test.rb
- test/test_helper.rb
- test/unit/appium_lib_core_test.rb
> make desired_capabilities name available in the capability

- CHANGELOG.md
- lib/appium_lib_core/device.rb
- lib/appium_lib_core/driver.rb
- script/commands.rb
- test/functional/android/android/device_test.rb
- test/functional/android/android/image_comparison_test.rb
- test/functional/android/webdriver/device_test.rb
- test/functional/android/webdriver/w3c_actions_test.rb
- test/functional/ios/webdriver/device_test.rb
- test/test_helper.rb
- test/unit/android/device/mjsonwp/image_comparison_test.rb
reduce warning in some cases such as overriding methods
> Fix warning

- CHANGELOG.md
- lib/appium_lib_core/android/device.rb
- lib/appium_lib_core/android/device/network.rb
- test/functional/android/android/device_test.rb
- test/functional/android/android/search_context_test.rb
- test/functional/android/driver_test.rb
- test/functional/android/webdriver/device_test.rb
- test/functional/android/webdriver/w3c_actions_test.rb
- test/test_helper.rb
- test/unit/android/device/w3c/commands_test.rb
https://github.com/appium/ruby_lib/issues/598
> Tweak test cases for espresso

- CHANGELOG.md
- README.md
- lib/appium_lib_core/common/base/search_context.rb
- test/functional/android/android/search_context_test.rb
- test/unit/driver_test.rb
https://github.com/appium/appium-espresso-driver/pull/386
> add android datamatcher

- lib/appium_lib_core/android/device.rb
- lib/appium_lib_core/common/base/bridge.rb
- lib/appium_lib_core/common/base/driver.rb
- lib/appium_lib_core/common/base/http_default.rb
- lib/appium_lib_core/common/base/search_context.rb
- lib/appium_lib_core/common/device/image_comparison.rb
- lib/appium_lib_core/common/wait.rb
- lib/appium_lib_core/common/ws/websocket.rb
- lib/appium_lib_core/driver.rb
- lib/appium_lib_core/ios/xcuitest/device.rb
Fix all of warnings in this yardoc
> clean yardoc style

- README.md
- lib/appium_lib_core/common/base/http_default.rb
- lib/appium_lib_core/driver.rb
- test/test_helper.rb
Extract appium_lib capability section
> Separate appium lib

- CHANGELOG.md
- lib/appium_lib_core/ios/xcuitest/device.rb
- lib/appium_lib_core/ios/xcuitest/device/screen.rb
- test/unit/ios/device/w3c/commands_test.rb
https://github.com/appium/appium-xcuitest-driver/pull/896/files
> Add pixel format

- azure-pipelines.yml
https://dev.azure.com/kazucocoa/ruby_lib_core_windows/_build/results?buildId=338
> add UNIT_TEST=true

- ci-jobs/functional/run_appium.yml
> add npm list task

- ci-jobs/functional_test.yml
Add running opencv4nodejs related tests
(Currently skipping them)
> install opencv4nodejs

- CHANGELOG.md
- lib/appium_lib_core/android/device.rb
- lib/appium_lib_core/android/uiautomator2/device.rb
- lib/appium_lib_core/common/base/bridge.rb
- lib/appium_lib_core/common/base/bridge/w3c.rb
- lib/appium_lib_core/common/base/driver.rb
- lib/appium_lib_core/common/base/http_default.rb
- lib/appium_lib_core/common/base/platform.rb
- lib/appium_lib_core/common/base/screenshot.rb
- lib/appium_lib_core/common/base/search_context.rb
- lib/appium_lib_core/common/device/image_comparison.rb
- lib/appium_lib_core/common/touch_action/multi_touch.rb
- lib/appium_lib_core/common/touch_action/touch_actions.rb
- lib/appium_lib_core/common/wait.rb
- lib/appium_lib_core/common/ws/websocket.rb
- lib/appium_lib_core/driver.rb
- lib/appium_lib_core/ios/xcuitest/device.rb
- lib/appium_lib_core/ios/xcuitest/device/screen.rb
- lib/appium_lib_core/patch.rb
- test/unit/ios/device/w3c/commands_test.rb
https://github.com/appium/appium-xcuitest-driver/pull/1005/files#diff-0b1b540a11a3485a5dcec9e05ed6f405R203 @ki4070ma
The code change is https://github.com/appium/ruby_lib_core/compare/master...KazuCocoa:add-filters?expand=1#diff-886c01c7cd3007f9f77b568f3420e8cdR37
> Add filters for start_recording_screen, ios, tweak yardoc

- .travis.yml
- lib/appium_lib_core/common/base/bridge.rb
- lib/appium_lib_core/device.rb
This PR is for Ruby 2.7, including a couple of warning fixes Appium ruby client can fix in this repository
> feat, ci: Fix a few warnings, add Ruby 2.7 in Travis

- lib/appium_lib_core/common/base/bridge.rb
- lib/appium_lib_core/common/base/driver.rb
more for https://github.com/appium/ruby_lib_core/pull/241
> fix warning in Ruby 2.7 more

- CHANGELOG.md
- lib/appium_lib_core/common/base/search_context.rb
- test/functional/android/android/search_context_test.rb
- test/unit/driver_test.rb
https://github.com/appium/appium/issues/13747
Haven't checked the behaviour yet
> feat: Add viewmatcher

- lib/appium_lib_core/common/base/http_default.rb
- lib/appium_lib_core/driver.rb
- test/unit/driver_test.rb
In the case create a instance with a custom http client
> refactor: move idempotency in driver

- test/functional/android/android/search_context_test.rb
> test: add allOf example

- appium_lib_core.gemspec
https://github.com/advisories/GHSA-2v5c-755p-p4gv
> chore: update faye-websocket

- ci-jobs/functional/run_appium.yml
- ci-jobs/functional/start-emulator.sh
- ci-jobs/functional_test.yml
- test/test_helper.rb
https://dev.azure.com/kazucocoa/ruby_lib_core/_build/results?buildId=2011&view=results
> ci: update for espresso

- .rubocop.yml
- appium_lib_core.gemspec
- lib/appium_lib_core.rb
- lib/appium_lib_core/android/device.rb
- lib/appium_lib_core/common/base/http_default.rb
- lib/appium_lib_core/common/base/search_context.rb
- lib/appium_lib_core/common/command/common.rb
- lib/appium_lib_core/common/command/mjsonwp.rb
- lib/appium_lib_core/common/command/w3c.rb
- lib/appium_lib_core/common/device/app_management.rb
- lib/appium_lib_core/common/wait.rb
- lib/appium_lib_core/ios/xcuitest/device.rb
- lib/appium_lib_core/windows/device.rb
- script/commands.rb
- test/functional/android/android/device_test.rb
- test/functional/android/webdriver/w3c_actions_test.rb
- test/functional/ios/ios/device_test.rb
- test/functional/ios/ios/mjpeg_server_test.rb
- test/functional/mac2/driver_test.rb
- test/test_helper.rb
- test/unit/driver_test.rb
related to https://github.com/appium/ruby_lib_core/pull/292
> feat: bump rubocop

- CHANGELOG.md
- lib/appium_lib_core/common/base/driver.rb
- lib/appium_lib_core/common/base/screenshot.rb
- lib/appium_lib_core/patch.rb
- test/functional/android/android/image_comparison_test.rb
- test/functional/ios/ios/image_comparison_test.rb
- test/unit/common/element_test.rb
I thought this method was already in Element...
> feat: append screenshot in element module as well

- CHANGELOG.md
- lib/appium_lib_core/driver.rb
- lib/appium_lib_core/mac2.rb
- lib/appium_lib_core/mac2/bridge.rb
- lib/appium_lib_core/mac2/device.rb
- lib/appium_lib_core/mac2/device/screen.rb
- test/test_helper.rb
- test/unit/mac2/device/w3c/commands_test.rb
I haven't added screen recording stuff yet
> feat: Add mac2 module and screen recording option

- CHANGELOG.md
- lib/appium_lib_core/common/base/driver.rb
- lib/appium_lib_core/common/device/image_comparison.rb
- test/test_helper.rb
- test/unit/android/device/w3c/image_comparison_test.rb
- test/unit/driver_test.rb
For https://github.com/appium/appium-base-driver
(Just adding arguments if needed)
> feat: add multiple and match_neighbour_threshold

- CHANGELOG.md
- ci-jobs/functional_test.yml
- lib/appium_lib_core/common/base/bridge/mjsonwp.rb
- lib/appium_lib_core/common/base/bridge/w3c.rb
- lib/appium_lib_core/common/base/driver.rb
- lib/appium_lib_core/common/base/has_location.rb
- test/unit/android/webdriver/mjsonwp/commands_test.rb
- test/unit/android/webdriver/w3c/commands_test.rb
> feat: add speed option

- appium_lib_core.gemspec
- ci-jobs/functional_test.yml
- docs/mobile_command.md
- lib/appium_lib_core/common/base/bridge.rb
- lib/appium_lib_core/common/base/driver.rb
- lib/appium_lib_core/common/base/screenshot.rb
- lib/appium_lib_core/common/device/value.rb
- lib/appium_lib_core/common/touch_action/touch_actions.rb
- lib/appium_lib_core/element.rb
- test/functional/android/android/image_comparison_test.rb
- test/functional/android/android/mobile_commands_test.rb
- test/functional/ios/ios/device_test.rb
- test/functional/ios/ios/image_comparison_test.rb
- test/functional/ios/ios/mobile_commands_test.rb
- test/functional/ios/webdriver/device_test.rb
- test/unit/android/device/w3c/definition_test.rb
- test/unit/android/device/w3c/keyboard_test.rb
- test/unit/image_element_test.rb
This does not include "Options" changes in capabilities.
Diff: https://github.com/SeleniumHQ/selenium/compare/selenium-4.0.0-beta-4...selenium-4.0.0-rc-1
> feat: se v4 rc1

- .github/workflows/codeql-analysis.yml
> ci: add codeql-analysis

- appium_lib_core.gemspec
- ci-jobs/functional/run_appium.yml
- lib/appium_lib_core/common/base/driver.rb
closes https://github.com/appium/ruby_lib_core/issues/389
> fix: remove unnecessary modules

- ci-jobs/functional/run_appium.yml
Reverts appium/ruby_lib_core#397
> Revert "ci: add a workaround to downgrade npm version for appium 2.0.0.beta.41"

- .rubocop.yml
- lib/appium_lib_core/common/base/bridge.rb
- test/unit/common_test.rb
as https://github.com/SeleniumHQ/selenium/blob/604c23b3a5224e9890a80bf5f97e4512d9586ec0/rb/lib/selenium/webdriver/remote/capabilities.rb#L295, keys as symbol should be converted but should not for string
> test: add test

- lib/appium_lib_core/common/device/value.rb
- test/unit/android/device/w3c/keyboard_test.rb
- test/unit/common/element_test.rb
> fix immediate value

- CHANGELOG.md
- appium_lib_core.gemspec
- lib/appium_lib_core/common/base/bridge.rb
- lib/appium_lib_core/common/base/has_location.rb
- lib/appium_lib_core/driver.rb
- test/unit/android/webdriver/w3c/commands_test.rb
instead of https://github.com/appium/ruby_lib_core/pull/445
> feat: define Appium::Location

- test/test_helper.rb
to see how they will help a bit
> test: add settings

- appium_lib_core.gemspec
> chore: bump selenium webdriver version

- lib/appium_lib_core/common/command.rb
- lib/appium_lib_core/element.rb
Similar to https://github.com/appium/python-client/pull/909
> chore: add deprecation marks

- lib/appium_lib_core/common/base/driver.rb
- lib/appium_lib_core/common/device/context.rb
- test/functional/android/android/device_test.rb
- test/functional/ios/driver_test.rb
closes https://github.com/appium/ruby_lib_core/issues/497
> test: tweak tests

- ci-jobs/functional/run_appium.yml
- lib/appium_lib_core/common/base/driver.rb
- lib/appium_lib_core/driver.rb
- test/functional/android/android/device_test.rb
- test/functional/android/driver_test.rb
- test/functional/ios/driver_test.rb
- test/functional/ios/ios/device_test.rb
- test/test_helper.rb
- test/unit/driver_test.rb
> feat: removed a few deprecated methods

- .github/workflows/functional-test.yml
First attempt with very rough script
> ci: run iOS func tests on GHA

- .github/workflows/functional-test.yml
- ci-jobs/functional_test.yml
- test/functional/android/android/device_test.rb
Not worked well yet ones are still in Azure. Some move to GHA
> ci: gha android
