appium/ruby_lib_core

lib/appium_lib_core/common/base/bridge.rb
lib/appium_lib_core/common/base/driver.rb
lib/appium_lib_core/common/command.rb
lib/appium_lib_core/common/device.rb
test/functional/android/android/device_test.rb
test/unit/android/device_test.rb
test/unit/ios/device_test.rb

Use `MJSONWP` instead of `OSS` to fit the other name rule.
(For the webdriver side, we use `OSS` for mobile JSON protocol.)

define MJSONWP instead of OSS

---

Rakefile
lib/appium_lib_core/common/device.rb
script/commands.rb
test/functional/android/android/device_test.rb
test/functional/ios/ios/device_test.rb
test/functional/ios/webdriver/device_test.rb
test/unit/script/commands_test.rb
test/unit/script/test_routes.js

We can get the diff which is not implemented in the Ruby client.
```
$ ruby script/commands.rb 
command: session/:session_id/rotation, method: [:get, :post]
command: session/:session_id/element/:id/page_index, method: [:get]
command: session/:session_id/receive_async_response, method: [:post]
command: session/:session_id/appium/device/finger_print, method: [:post]
command: session/:session_id/appium/device/send_sms, method: [:post]
command: session/:session_id/appium/device/gsm_call, method: [:post]
command: session/:session_id/appium/device/gsm_signal, method: [:post]
command: session/:session_id/appium/device/gsm_voice, method: [:post]
command: session/:session_id/appium/device/power_capacity, method: [:post]
command: session/:session_id/appium/device/power_ac, method: [:post]
command: …
```

add script to get diff commands

---

CHANGELOG.md
lib/appium_lib_core/common/base/bridge.rb

Fix createSession to work after https://github.com/appium/appium/pull/9791

fix creating sessions

---

CHANGELOG.md
appium_lib_core.gemspec
lib/appium_lib_core/common/base/bridge.rb
test/unit/common_test.rb

ref: https://github.com/appium/ruby_lib_core/pull/31#issuecomment-352667828
```
pry(#<Appium::Core::Base::Bridge>)> add_prefix(desired_capabilities)
=> #<Selenium::WebDriver::Remote::W3C::Capabilities:0x007fe564253748
@capabilities=
{:proxy=>nil,
:platformName=>:ios,
"appium:automationName"=>"XCUITest",
"appium:app"=>"/Users/kazuaki/GitHub/ruby_lib_core/test/functional/app/UICatalog.app",
"appium:platformVersion"=>"10.3",
"appium:deviceName"=>"iPhone Simulator",
"appium:useNewWDA"=>true,
"appium:some_capability"=>"some_capability"}>
```
```
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"ios","automationName":"XCUITest","app":"/Users/kazuaki/GitHub/ruby_lib_core/test/functional/app/UICatalog.app","platformVersion":"10.3","deviceName":"iPhone …
```

add adding appium-prefix

---

CHANGELOG.md
lib/appium_lib_core/common/base/bridge.rb
test/functional/android/android/create_session_test.rb
test/functional/ios/webdriver/create_session_test.rb

The change is https://github.com/appium/ruby_lib_core/commit/360ba58a01a1b5b8f6abb034a146508125a7f213
---

Switchable w3c format caps from capabilities

---

CHANGELOG.md
lib/appium_lib_core/driver.rb

Missing symbol set in set_automation_name_if_nil method #50

apply intern

---

lib/appium_lib_core/android/device/emulator.rb
lib/appium_lib_core/common/command.rb
lib/appium_lib_core/common/device.rb
test/unit/android/device_test.rb
test/unit/android/device_w3c_test.rb
test/unit/script/commands_test.rb

closes:
- session/:session_id/appium/device/toggle_location_services #25
- session/:session_id/appium/device/toggle_wifi #24
- session/:session_id/appium/device/toggle_data #23

add toggles

---

CHANGELOG.md
lib/appium_lib_core.rb
lib/appium_lib_core/android/device.rb
lib/appium_lib_core/common/command.rb
lib/appium_lib_core/common/device.rb
lib/appium_lib_core/device/clipboard_content_type.rb
lib/appium_lib_core/ios/device.rb
test/functional/android/android/device_test.rb
test/functional/ios/ios/device_test.rb
test/unit/android/device_test.rb
test/unit/android/device_w3c_test.rb
test/unit/ios/device_test.rb
test/unit/ios/device_w3c_test.rb
test/unit/script/commands_test.rb

https://github.com/appium/appium-base-driver/pull/199/files
- And make sure they work
----
note: for android
```
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:209)
at android.os.Handler.<init>(Handler.java:123)
at android.content.ClipboardManager$2.<init>(ClipboardManager.java:69)
at android.content.ClipboardManager.<init>(ClipboardManager.java:69)
at android.app.SystemServiceRegistry$12.createService(SystemServiceRegistry.java:276)
at android.app.SystemServiceRegistry$12.createService(SystemServiceRegistry.java:275)
at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:884)
at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java …
```

add clipboard api

---

CHANGELOG.md
lib/appium_lib_core/common/base/bridge/w3c.rb
test/functional/ios/webdriver/w3c_actions_test.rb

We can see the diff:
```
[debug] [XCUITest] Received the following W3C actions: [
[debug] [XCUITest]   {
[debug] [XCUITest]     "type": "pointer",
[debug] [XCUITest]     "id": "mouse",
[debug] [XCUITest]     "actions": [ ... ],
[debug] [XCUITest]     "parameters": {
[debug] [XCUITest]       "pointerType": "mouse"
[debug] [XCUITest]     }
[debug] [XCUITest]   }
[debug] [XCUITest] ]
[debug] [XCUITest] Preprocessed actions: [
[debug] [XCUITest]   {
[debug] [XCUITest]     "type": "pointer",
[debug] [XCUITest]     "id": "mouse",
[debug] [XCUITest]     "actions": [ ... ],
[debug] [XCUITest]     "parameters": {
[debug] [XCUITest]       "pointerType": "touch" # Work as 'touch'
[debug] [XCUITest]     }
[debug] [XCUITest]   }
[debug] [XCUITest] ]
```
----
full
```
[debug] [XCUITest] Executing …
```

remove overrided action

---

lib/appium_lib_core/android/device.rb
lib/appium_lib_core/common/command.rb
lib/appium_lib_core/common/device.rb
test/functional/android/android/device_test.rb
test/functional/android/driver_test.rb
test/functional/android/patch_test.rb
test/functional/android/webdriver/device_test.rb
test/functional/android/webdriver/w3c_actions_test.rb
test/test_helper.rb
test/unit/android/device_test.rb
test/unit/android/device_w3c_test.rb
test/unit/ios/device_test.rb
test/unit/ios/device_w3c_test.rb

Getting rid of method generation for no argument commands to increase IDE support. (With RubyMine, we can't use code jump and assistants with before implementation, for example.)

get ride of auto method generation to enhance ide support

---

CHANGELOG.md
lib/appium_lib_core/device/touch_actions.rb
test/functional/android/android/device_test.rb
test/functional/ios/ios/device_test.rb

The hotfix was used by `ruby_lib` to keep compatibility.

Remove hotfix xcuitest pinch zoom

---

lib/appium_lib_core/common/base/http_default.rb

Ruby core inherits selenium webdriver and define `DEFAULT_HEADERS` here.
I've added `Content-Type` as same as webdriver by default.
(I know it can case-insensitive, but it's because of following webdriver.)

set default content type

---

CHANGELOG.md
lib/appium_lib_core/device.rb
test/functional/android/android/device_test.rb

Add custom format and an example : https://github.com/appium/appium-android-driver/pull/378
```ruby
@@driver.device_time('+%Y') #=> "2018"
```
---

add date format for Android

---

CHANGELOG.md
lib/appium_lib_core/driver.rb
test/unit/common_test.rb

When I checked ruby_lib code, i found below case.
https://wiki.saucelabs.com/display/DOCS/Uploading+Mobile+Applications+to+Sauce+Storage+for+Testing
Thus, I'd like to use `@caps[:app]` directly if it isn't http/s or local path with information log level.

use :app without modifications

---

CHANGELOG.md
lib/appium_lib_core/common/base/bridge/w3c.rb

avoid a warning for intentional definition
https://github.com/appium/ruby_lib/issues/800

silence warning for pointeractions

---

CHANGELOG.md
lib/appium_lib_core/patch.rb
test/functional/android/patch_test.rb
test/functional/ios/patch_test.rb
test/unit/android/device/w3c/commands_test.rb
test/unit/ios/device/w3c/commands_test.rb

`attribites` we can get depends on platforms. Thus, it's easy to get me them based on method missing.

use method missing for getting attributes

---

CHANGELOG.md
lib/appium_lib_core/common/base/bridge/w3c.rb
lib/appium_lib_core/common/base/driver.rb
lib/appium_lib_core/common/command/w3c.rb
test/unit/android/device/mjsonwp/commands_test.rb
test/unit/android/device/w3c/commands_test.rb
test/unit/script/commands_test.rb

With W3C, it will be
```
driver.action.send_keys('xxxx').perform
```
But we need to implement `type: key` in action in server side => example https://github.com/appium/appium-espresso-driver/pull/192/files

port send keys for an active element

---

CHANGELOG.md
lib/appium_lib_core/driver.rb

closes _Incorrect calls to `raise` in `set_implicit_wait_by_default` #130_

Fix raising error format and remove unnecessary fixme

---

CHANGELOG.md
lib/appium_lib_core/patch.rb

Raise an error unexpected method missing: method missing happened against `:to_hash`

fix unexpected method missing

---

CHANGELOG.md
lib/appium_lib_core/common/base/bridge.rb
test/unit/common_test.rb

Fix w3c capabilities in handshake #137 
The capability is following selenium-webdriver.
https://github.com/SeleniumHQ/selenium/blame/07a18746ff756e90fd79ef253a328bd7dfa9e6dc/rb/lib/selenium/webdriver/remote/bridge.rb

fix capabilities for selenium grid

---

CHANGELOG.md
lib/appium_lib_core/android/device/clipboard.rb
lib/appium_lib_core/common/base/driver.rb
lib/appium_lib_core/common/base/search_context.rb
lib/appium_lib_core/common/device/file_management.rb
lib/appium_lib_core/common/device/image_comparison.rb
lib/appium_lib_core/ios/device/clipboard.rb
test/functional/android/android/device_test.rb
test/functional/android/android/mobile_commands_test.rb
test/functional/ios/ios/mobile_commands_test.rb
test/functional/ios/webdriver/device_test.rb
test/unit/android/device/mjsonwp/image_comparison_test.rb
test/unit/android/device/w3c/image_comparison_test.rb

- Send base64 format following RFC 4648
- Just make format strict. I tested this does not affect node front Appium server with some image/content scenarios
---
note:
WDA => Appium was probably following RFC 2045 since the data had `\n`.
Appium returns RFC 4648, basically. (nodejs's base64)
Ruby can decode both of them with `Base64.decode64` (I have not changed decode related code)
https://ruby-doc.org/stdlib-2.5.3/libdoc/base64/rdoc/Base64.html

Sends strict base64 format to server

---

lib/appium_lib_core/patch.rb

While I was trying to run to_yaml on a hash containing an appium element, an error was raised,
since the class is missing a `encode_with` method.
Since the method_missing method itself has the wrong signature, it failed actually with wrong number of arguments.
This PR fixes the signature of method_missing inside patch.rb
FYI I ended up adding encode_with as well:
```ruby
def encode_with coder
coder['name'] = name
end
```

fix method_missing not having the correct signature

---

CHANGELOG.md
lib/appium_lib_core/android/device.rb
test/functional/android/android/device_test.rb
test/unit/android/device/mjsonwp/commands_test.rb
test/unit/android/device/w3c/commands_test.rb

I noticed ruby send blank values in start activity.
https://github.com/appium/appium-espresso-driver/pull/378
I tested in espresso/uiautomator2

Donotsend unused value start activity

---

CHANGELOG.md
lib/appium_lib_core/common/base/driver.rb
lib/appium_lib_core/common/base/http_default.rb
lib/appium_lib_core/driver.rb
test/test_helper.rb
test/unit/driver_test.rb

This is an experimental feature to improve requests peformance in a particular case.
If a server returns `directConnectProtocol`, `directConnectHost`, `directConnectPort` and `directConnectPath` as a part of the response of create session, Ruby client send following requests to them.
This feature improves performance if a user handles requests via proxy server between clients to Appium servers. In this context, the proxy server is similar to SeleniumGrid.
```
client <--> proxy server <---> appium server <-> devices
`-> appium server <-> devices
```
```
client <--------> appium server <-> devices
`---> appium server <-> devices
```
This idea was discussed with @jlipps

Experimental add direct host

---

CHANGELOG.md
lib/appium_lib_core/driver.rb
test/functional/android/android/mjpeg_server_test.rb
test/test_helper.rb
test/unit/android/webdriver/w3c/timeouts_test.rb
test/unit/common_test.rb
test/unit/driver_test.rb

Or remove set timeout by default in ruby_lib_core. Sets it in the ruby_lib side.
Otherwise, this change will be breaking change.
Will merge and consider when we introduce another breaking changes

set default zero implicit wait

---

test/functional/android/android/device_test.rb
test/functional/ios/ios/device_test.rb

current master fails this PR's test cases for find element by image/s
https://github.com/appium/appium-base-driver/compare/master...KazuCocoa:fix-find-element-wrong-coordinate?expand=1

add strict find image

---

lib/appium_lib_core/android/device/emulator.rb
test/unit/android/device/mjsonwp/commands_test.rb
test/unit/android/device/w3c/commands_test.rb
test/unit/script/test_routes.js

Fixed on https://github.com/appium/appium-base-driver/pull/308

Fixed typo signalStrengh

---

.rubocop.yml
CHANGELOG.md
lib/appium_lib_core/android/device.rb
test/unit/android/device/w3c/commands_test.rb

```
'/wd/hub/session/:sessionId/appium/device/start_activity': {
POST: {
command: 'startActivity',
payloadParams: {
required: ['appPackage', 'appActivity'],
optional: ['appWaitPackage', 'appWaitActivity', 'intentAction',
'intentCategory', 'intentFlags', 'optionalIntentArguments', 'dontStopAppOnReset']
}
}
},
```
- https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md#uiautomator-1--2

add arguments for start activity

---

ci-jobs/functional_test.yml

Suddenly, below error started for all iOS tests on Azure.
Hosted macOS probably got issues, while hosted macOS high sierra worked as same as previous hosted macOS. (Will contact Azure support about it) 
```
test_batch#AppiumLibCoreTest::DriverTest (55.14s)
Selenium::WebDriver::Error::UnknownError:         Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain CFBundleShortVersionString.
Ensure your bundle contains a CFBundleShortVersionString.
UnknownError: An unknown server-side error occurred while processing the …
```

ci: use macOS High Sierra for iOS since it fails on macOS host

---

CHANGELOG.md
ci-jobs/functional_test.yml
lib/appium_lib_core/common/device/value.rb
test/functional/android/android/device_test.rb
test/functional/android/android/image_comparison_test.rb
test/functional/android/webdriver/device_test.rb
test/unit/android/device/mjsonwp/keyboard_test.rb
test/unit/android/device/w3c/keyboard_test.rb
test/unit/common/element_test.rb

Run Android tests against Espresso driver, too.
found: https://github.com/appium/appium-espresso-driver/pull/478

Add tests for espresso driver

---

ci-jobs/functional_test.yml

Suddenly, below started
```
(node:2911) UnhandledPromiseRejectionWarning: Error: Cannot find module '/Users/vsts/agent/2.155.1/work/1/s/package.json'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (internal/modules/cjs/helpers.js:25:18)
at /usr/local/lib/node_modules/opencv4nodejs/node_modules/opencv-build/build/install.js:75:43
at step (/usr/local/lib/node_modules/opencv4nodejs/node_modules/opencv-build/build/install.js:32:23)
at Object.next (/usr/local/lib/node_modules/opencv4nodejs/node_modules/opencv-build/build/install.js:13:53)
at /usr/local/lib/node_modules/opencv4nodejs/node_modules/opencv-build/build/install.js:7:71
at …
```

ci: disable opencv to avoid installation error on ci

---

ci-jobs/functional/run_appium.yml

Below returned 503 error.. and maybe i can remove this for ruby test suite
```
[13:51:44] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/2.44/chromedriver_mac64.zip...
```

ci: remove Chromedriver option for install

---

CHANGELOG.md
lib/appium_lib_core/common/base/http_default.rb
lib/appium_lib_core/driver.rb
test/unit/android/device/mjsonwp/commands_test.rb
test/unit/android/device/w3c/commands_test.rb
test/unit/driver_test.rb

https://github.com/appium/ruby_lib_core/issues/258
Not tested with Appium

feat: Add x idempotency header

---

CHANGELOG.md
lib/appium_lib_core/driver.rb
test/test_helper.rb

fix https://github.com/appium/ruby_lib_core/issues/262

fix: x-idempotency-key only for a new session

---

CHANGELOG.md
lib/appium_lib_core/common/base/search_context.rb

https://github.com/SeleniumHQ/selenium/blob/da134d42e586efb5678dd40f8a648ab13ef6a3f3/rb/CHANGES#L323
I tested with specifying selenium-webdriver `3.14.1` on my local to ensure this did not need to update dependencies.
https://github.com/appium/ruby_lib/issues/869
I also override error as `time out` or `timeout`. Both can overt to proper timeout error with this change. It should be safe to merge if all tests are green.

feat: Remove timeout deprecated

---

ci-jobs/functional_test.yml

Hm, on 30 emulator, `shell input text /normal/` is text type. Only this action failed.
```
@driver.execute_script 'mobile: performEditorAction', { action: 'normal' }
```
```
[HTTP] --> POST /wd/hub/session/56b4835f-8ea1-4623-ab83-d79c82a6a1ce/execute/sync
[HTTP] {"script":"mobile: performEditorAction","args":[{"action":"normal"}]}
[debug] [W3C (56b4835f)] Calling AppiumDriver.execute() with args: ["mobile: performEditorAction",[{"action":"normal"}],"56b4835f-8ea1-4623-ab83-d79c82a6a1ce"]
[AndroidDriver] Executing native command 'mobile: performEditorAction'
[debug] [ADB] Performing editor action: normal
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get secure default_input_method'
[debug] [ADB] Running …
```

ci: bump ci android version

---

test/functional/ios/ios/device_test.rb
test/functional/ios/patch_test.rb
test/functional/ios/webdriver/device_test.rb
test/functional/ios/webdriver/w3c_actions_test.rb

since Appium 1.19.1
https://github.com/appium/WebDriverAgent/pull/416#issuecomment-718214299
Uses `value` (could be `wdValue` as well) since the key name is printed in source tree
---
This should work on the previous versions, too.

test: use predicate instead of name for 'value'

---

lib/appium_lib_core/driver.rb

No special change, but for https://github.com/appium/appium-safari-driver
So far, it should be the same as W3C-SafariDriver. It is almost the same as Selenium client.

feat: add safari and geckodriver

---

lib/appium_lib_core/common/device/app_management.rb

**What's wrong?**
`args[:options]` object is created only if _all_ optional arguments are present. This leads to error in next lines.
**How to reproduce?**
Call `install_app` method by setting not all optional arguments.

Fixed .install_app args options bug

---

.github/workflows/unittest.yml
.rubocop.yml
CHANGELOG.md
appium_lib_core.gemspec
test/functional/android/android/device_test.rb
test/functional/android/android/mobile_commands_test.rb
test/functional/ios/driver_test.rb
test/functional/ios/ios/mobile_commands_test.rb
test/unit/android/device/w3c/execute_driver_test.rb

Selenium Ruby client will be 2.5 base. (4.0.0a4 was 2.4 base, so let's bump to it for now.)

feat: bump supported ruby version

---

CHANGELOG.md
lib/appium_lib_core/common/base/bridge.rb
test/functional/android/webdriver/create_session_test.rb
test/functional/ios/webdriver/create_session_test.rb
test/unit/common_test.rb

The forceMjsonwp was a temporary solution to keep MJSONWP.
Selenium 4 is going to support only W3C spec, and current Appium already spent a long time with W3C.
Ruby lib will drop lower Ruby versions soon, so it's a good time to drop it as well.

feat: drop forcemjsonwp

---

CHANGELOG.md
lib/appium_lib_core/common/base/bridge/mjsonwp.rb
lib/appium_lib_core/common/base/bridge/w3c.rb
lib/appium_lib_core/common/base/driver.rb
lib/appium_lib_core/common/base/remote_status.rb
lib/appium_lib_core/driver.rb
test/test_helper.rb
test/unit/android/webdriver/mjsonwp/commands_test.rb
test/unit/android/webdriver/w3c/commands_test.rb

Let me return always hash for `appium_server_version` instead of raising an issue.
This will prevent some error cases in https://github.com/appium/ruby_lib/blob/219181d80f3b86999706f90a68996945fdc7b1d0/lib/appium_lib/driver.rb#L556 no to block the creation.

feat: always return {} in appium_server_version for errors

---

CHANGELOG.md
lib/appium_lib_core/common/base/bridge.rb
lib/appium_lib_core/common/base/bridge/mjsonwp.rb
lib/appium_lib_core/common/base/bridge/w3c.rb
lib/appium_lib_core/common/base/driver.rb
lib/appium_lib_core/common/error.rb
test/test_helper.rb
test/unit/android/webdriver/mjsonwp/commands_test.rb
test/unit/android/webdriver/w3c/commands_test.rb

https://github.com/appium/ruby_lib_core/issues/306 by exposing `::Appium::Core::Device.add_endpoint_method` as a public method of a driver instance

feat: allow to add commands dynamically

---

CHANGELOG.md
lib/appium_lib_core/common/base/bridge/mjsonwp.rb
lib/appium_lib_core/common/base/bridge/w3c.rb
lib/appium_lib_core/common/base/driver.rb
test/unit/android/webdriver/mjsonwp/commands_test.rb
test/unit/android/webdriver/w3c/commands_test.rb

https://github.com/appium/java-client/pull/1506#discussion_r698003140
Instead, this PR leaves a log as debug.

feat: allow to override an existing method by add_command

---

lib/appium_lib_core/common/base/bridge.rb
test/unit/common_test.rb

fix: sends [{}]

---

lib/appium_lib_core/common/base/driver.rb
lib/appium_lib_core/common/device/app_management.rb
test/unit/android/device/w3c/app_management_test.rb

xcuitest driver wants to allow options in https://github.com/appium/appium-xcuitest-driver#mobile-installapp for `install_app` as well.
This will need doc more.

feat: do not restrict options in install_app

---

lib/appium_lib_core/common/base/driver.rb

A regression in v5 for https://github.com/appium-userland/appium-flutter-driver/tree/master/finder/ruby/lib

fix: make bridge attribute non-private for flutter finder

---

.github/workflows/unittest.yml
README.md
ci-jobs/functional/run_appium.yml
ci-jobs/functional_test.yml
release_notes.md
test/functional/android/android/image_comparison_test.rb
test/functional/ios/ios/image_comparison_test.rb
test/test_helper.rb
test/unit/driver_test.rb

https://github.com/appium/appium-plugins/pull/73 will be needed

ci: run with appium 2.0

---

CHANGELOG.md
lib/appium_lib_core/common/base/bridge.rb
lib/appium_lib_core/common/base/capabilities.rb
lib/appium_lib_core/driver.rb
test/unit/appium_lib_core_test.rb
test/unit/common_test.rb
test/unit/driver_test.rb

fixes https://github.com/appium/ruby_lib/issues/945
Removes `Appium.symbolize_keys` which makes capability keys to symbol forcefully.
The code was copied from legacy ruby_lib code to ruby_lib_core. I was not sure the root motivation for that, but now ruby_lib_core converts capability keys which does not have `appium:` as string.

fix: remove symbolize

---

CHANGELOG.md
lib/appium_lib_core.rb
lib/appium_lib_core/common/error.rb
lib/appium_lib_core/driver.rb
test/unit/appium_lib_core_test.rb
test/unit/common_test.rb
test/unit/driver_test.rb

https://github.com/appium/ruby_lib/issues/945
They have a case what gives `caps` and `appium_lib` as string. I expected they were Symbols, but previously they could be String. The removed method converted string to symbol implicitly, so it worked.
This behavior is unexpected right now, so this PR start showing deprecation message while keeping the conversion behavior for the top level keys.

fix: keep the legacy behavior partially, showing a warning message instead for now

---

.rubocop.yml
lib/appium_lib_core/android/device.rb
lib/appium_lib_core/common/base/bridge.rb
test/test_helper.rb
test/unit/android/device/w3c/execute_cdp_test.rb

```
ERROR AppiumLibCoreTest::Android::Device::W3C::ExecuteCDPTest#test_execute_cdp_chrome (1.38s)
Minitest::UnexpectedError:         NoMethodError: undefined method `send_command' for #<Appium::Core::Base::Bridge:0x00007ff396051ba8>
Did you mean?  add_command
test_command
/Users/kazu/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.9.0/lib/selenium/webdriver/common/driver_extensions/has_cdp.rb:31:in `execute_cdp'
/Users/kazu/GitHub/ruby_lib_core/test/unit/android/device/w3c/execute_cdp_test.rb:49:in `test_execute_cdp_chrome'
```

fix: execute cdp for chrome session

---

.rubocop.yml
lib/appium_lib_core/common/base/http_default.rb
test/test_helper.rb

Refer to https://github.com/SeleniumHQ/selenium/pull/12141#discussion_r1217364496
Current ruby_lib_core's headers modification way is not good as monchy-pactch. Actually the Watir way is sufficient and makes more sense for this usage. Let me modify current implementation to reduce a monkey patche

refactor: define UA in requests is sufficisnet instead

---

lib/appium_lib_core/android/device.rb
lib/appium_lib_core/android/device/auth_finger_print.rb
lib/appium_lib_core/android/device/network.rb
lib/appium_lib_core/android/device/performance.rb
lib/appium_lib_core/android/device/screen.rb
lib/appium_lib_core/common/base/driver.rb
lib/appium_lib_core/ios/xcuitest/device.rb

https://github.com/appium/ruby_lib_core/issues/463
Or use `mobile:` as the backend call.

chore: add deprecation marks

---

test/functional/android/android/search_context_test.rb
test/functional/ios/ios/search_context_test.rb
test/unit/driver_test.rb
test/unit/image_element_test.rb

add tests to cover https://github.com/appium/ruby_lib_core/pull/480 for future

test: add tests for future

---

lib/appium_lib_core/common/base/driver.rb
lib/appium_lib_core/common/device/context.rb
lib/appium_lib_core/device.rb

More removal https://github.com/appium/ruby_lib_core/issues/463

chore: remove switch_to_default_context

---

CHANGELOG.md
lib/appium_lib_core.rb
lib/appium_lib_core/common/base/capabilities.rb
lib/appium_lib_core/driver.rb
test/unit/common_test.rb
test/unit/driver_test.rb

This is a breaking change for users who use symbols in their capabilities with snake case.
(Just I'd like to send caps as-is what we configured.)

feat: do not conver to camel case automatically

---

.github/workflows/functional-test.yml
lib/appium_lib_core/android/device.rb
lib/appium_lib_core/android/device/clipboard.rb
lib/appium_lib_core/android/device/emulator.rb
lib/appium_lib_core/android/device/screen.rb
lib/appium_lib_core/common/base/capabilities.rb
lib/appium_lib_core/common/base/screenshot.rb
lib/appium_lib_core/common/device/image_comparison.rb
lib/appium_lib_core/common/device/screen_record.rb
lib/appium_lib_core/common/error.rb
lib/appium_lib_core/driver.rb
lib/appium_lib_core/element.rb
lib/appium_lib_core/ios/device/clipboard.rb
test/test_helper.rb

Current error is mixed, general predefined error and Appium/Selenium errors. This PR raises Appium's own error if it was not by Selenium so that uses can handle this lib specific error if needed.

feat: raise its own defined errors

---

.gitignore
Rakefile
Steepfile
appium_lib_core.gemspec
rbs_collection.lock.yaml
rbs_collection.yaml
sig/gems/selenium/abstract_event_listener.rbs
sig/gems/selenium/capabilities.rbs
sig/gems/selenium/default.rbs
sig/gems/selenium/driver.rbs
sig/gems/selenium/has_session_id.rbs
sig/gems/selenium/has_web_storage.rbs
sig/gems/selenium/uploads_files.rbs
sig/lib/appium_lib_core.rbs
sig/lib/appium_lib_core/common/base/capabilities.rbs
sig/lib/appium_lib_core/common/base/driver.rbs
sig/lib/appium_lib_core/common/base/driver_settings.rbs
sig/lib/appium_lib_core/common/base/has_location.rbs
sig/lib/appium_lib_core/common/base/has_network_connection.rbs
sig/lib/appium_lib_core/common/base/http_default.rbs
sig/lib/appium_lib_core/common/base/platform.rbs
sig/lib/appium_lib_core/common/base/remote_status.rbs
sig/lib/appium_lib_core/common/base/rotable.rbs
sig/lib/appium_lib_core/common/base/screenshot.rbs
sig/lib/appium_lib_core/common/wait.rbs
sig/lib/appium_lib_core/device.rbs
sig/lib/appium_lib_core/driver.rbs

This PR is the first of several PRs to add RBS support to the full ruby_lib_core project
Key things added to this PR:
- Steep gem as a development dependency:
- Steep is a type validation gem https://github.com/soutaro/steep, that depends on RBS and typeprof, the goal of steep is to allow us to check for type issues
- RBS gem collection: Several commonly used gems do not have RBS files, so the ruby community created a collection used by RBS to avoid us having to declare all the commonly used gems every time: https://github.com/ruby/gem_rbs_collection
- Sig folder: This is the signature folder and is where all of our RBS files will be located
- Rake task to run type checks: there is a rake task now, named steep that makes it easier to run a check from your preferred IDE
- Steepfile: this …

feat: RBS setup for core appium library

---

sig/gems/selenium/common.rbs
sig/lib/appium_lib_core/common/device/battery_status.rbs
sig/lib/appium_lib_core/ios/xcuitest/device/battery.rbs
sig/lib/appium_lib_core/version.rbs

This PR is the second PR in our efforts to bring full RBS support to the ruby_lib_core
The following RBS files are added for the respective classes and modules:
- Common
- Battery
- Battery Status
- Version
Before the PR:
After the PR:
We want to add type support to the core library as specified here #296 so it's easier for new contributors to understand what the methods are expecting and returning.
We also want eventually to be able to run automatic type checks to avoid type errors, and we would like for the RBS files to serve as documentation so the contributors do not need to write as many comments and speed up their flow.

feat: Take down steep issues from 589 to 552

---

lib/appium_lib_core/driver.rb
test/unit/appium_lib_core_test.rb
test/unit/driver_test.rb

fixes https://github.com/appium/ruby_lib_core/issues/569
This fix will fix ruby_lib as well. e.g. https://github.com/appium/ruby_lib/blob/0d1c2b87b8f2ac456372bf4cbb2441fffae5cf27/lib/appium_lib/driver.rb#L208-L243

fix instance variables of device and automation_name

---

lib/appium_lib_core/driver.rb
sig/lib/appium_lib_core/driver.rbs

Remove one small deprecation mark method.

feat!: remove deprecated quit_driver

---

lib/appium_lib_core/common/command.rb
lib/appium_lib_core/driver.rb
test/unit/driver_test.rb

Replace the endpoint call from `session/:session_id/log/types` to `session/:session_id/se/log/types`. This should not cause any issues recent Appium versions. Possibly old one such as Appium 1.20 or lower, or around could have an issue but they are pretty old today.

feat: use /se/log and /se/log/types for logs

---

lib/appium_lib_core/common/base/driver.rb
lib/appium_lib_core/common/base/search_context.rb
lib/appium_lib_core/element.rb

closes https://github.com/appium/ruby_lib_core/issues/587

chore: add module and class to make them readable in docs

---

.github/workflows/functional-test.yml
lib/appium_lib_core/common/base.rb
lib/appium_lib_core/common/base/bidi_bridge.rb
lib/appium_lib_core/common/base/bridge.rb
lib/appium_lib_core/common/base/driver.rb
lib/appium_lib_core/driver.rb
sig/lib/appium_lib_core/common/base/bidi_bridge.rbs
sig/lib/appium_lib_core/common/base/bridge.rbs
sig/lib/appium_lib_core/common/base/search_context.rbs
test/functional/android/webdriver/bidi_test.rb
test/unit/driver_test.rb

https://github.com/appium/ruby_lib_core/issues/629

feat: add BiDi bridge
